version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Ecommerce_web
    command: sh entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/Ecommerce
      - ./media:/Ecommerce/media
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      
      POSTGRES_DB: Ecommerce_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    container_name: postgres_Ecommerce
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_Ecommerce
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A Ecommerce worker --loglevel=info
    volumes:
      - .:/Ecommerce
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Ecommerce_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data: